TurtlyPredifinedDirections = (315,
                              135,
                              45,
                              225,
                              225,
                              45,
                              135,
                              315,
                              270,
                              90,
                              0,
                              180)
